# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04a5a993272d9a85704a5cb8cf56c0b87051ad14c54a94cca33f098326c582181060e48ee8d6d43cbebd380f2d0a058ef0e1180581bcfed6f23f5bc4fbe32bce

test:
  secret_key_base: 331b6a6e5433adb66cdf517642fbd63813605f9d2c1e13919b2a2ea9489986f4f8985392e4415d3b7713442a625718a0908282bfd377f7cf6a9fcba81d6c0139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
